# Generated by Django 3.0.3 on 2020-02-03 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный номер пользователя', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Имя пользователя', max_length=100)),
                ('last_name', models.CharField(help_text='Фамилия пользователя', max_length=100)),
                ('log_in', models.BooleanField(help_text='Состояние авторизации пользователя')),
                ('facebook_id', models.CharField(help_text='Facebook ID пользователя', max_length=100)),
                ('session_id', models.CharField(help_text='Id сессии пользователя ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный номер воспоминания', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название воспоминания', max_length=200)),
                ('description', models.TextField(help_text='Описание воспоминания', max_length=2000)),
                ('remembers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remember.User')),
            ],
        ),
    ]
