# Generated by Django 3.0.3 on 2020-02-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remember',
            name='remembers',
        ),
        migrations.AddField(
            model_name='remember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remember.User'),
        ),
    ]
