# Generated by Django 3.0.3 on 2020-02-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0002_auto_20200203_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remember',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
