# Generated by Django 3.0.2 on 2020-02-04 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remember', '0003_auto_20200203_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='remember',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remember',
            name='map_coordinates',
            field=models.CharField(default='0.0;0.0', help_text='Координаты карты', max_length=100),
        ),
    ]
